stages:
    - test
    - build-docker-master
    - build-docker-dev
    - deploy-seldon-master

variables:
    IMAGE_NAME: "cifar10-seldon"
    PROD_TAG: "prod"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

test:
  image: "determinedai/environments:py-3.7-pytorch-1.7-tf-1.15-cpu-0.11.0"
  stage: test
  script:
    - pip install --upgrade pip
    - pip install determined==0.15.1
    - python -m unittest -v cifar10/test/test_model_accuracy.py

build-docker-master:
  # Official docker image.
  image: docker:latest
  stage: build-docker-master
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_USER/$IMAGE_NAME:$PROD_TAG -f cifar10/deploy/Dockerfile .
    - docker push "$CI_REGISTRY_USER/$IMAGE_NAME:$PROD_TAG"
  only:
    - master
  needs: ["test"]

build-docker-dev:
   # Official docker image.
  image: docker:latest
  stage: build-docker-dev
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_USER/$IMAGE_NAME:$CI_COMMIT_SHA -f cifar10/deploy/Dockerfile .
    - docker push "$CI_REGISTRY_USER/$IMAGE_NAME:$CI_COMMIT_SHA"
  only:
    # We want this job to be run on branches only.
    - branch
  needs: ["test"]

deploy-seldon-master:
    stage: deploy-seldon-master
    image: bitnami/kubectl
    script:
      - echo $KUBE_URL
      - echo $KUBECONFIG
      - kubectl apply -f cifar10/deploy/deploy.yaml
    only:
    - master