variables:
    IMAGE_NAME: "cifar10-seldon"
    PROD_TAG: "prod"
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_USER/$IMAGE_NAME:$PROD_TAG -f cifar10/deploy/Dockerfile .
    - docker push "$CI_REGISTRY_USER/$IMAGE_NAME:$PROD_TAG"
  only:
    - master