tests:
  image: "determinedai/environments:py-3.7-pytorch-1.7-tf-1.15-cpu-0.11.0"
  stage: test
  script:
    - pip install --upgrade pip
    - pip install determined==0.15.1
    - python -m unittest -v cifar10/test/test_model_accuracy.py