apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: news-classifier
  namespace: default
spec:
  name: news-classifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: jabalt/bbc-seldon:prod
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
    graph:
      children: []
      parameters:
        - name: det_master
          type: STRING
          value: "http://10.64.140.43:8080/"
        - name: model_name
          type: STRING
          value: "news-classifier"
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: news-classifier
    replicas: 1